version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: transactions_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  wiremock:
    image: wiremock/wiremock:3.9.1
    volumes:
      - ./wiremock-mappings:/home/wiremock/mappings
    ports:
      - "9090:8080"

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      wiremock:
        condition: service_started
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/transactions_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      PROVIDER_BASE_URL: http://wiremock:8080
    ports:
      - "8080:8080"

volumes:
  pgdata:
